pipeline:
  name: hosted-build
  identifier: hostedbuild
  projectIdentifier: DanF
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo "hi"
                      echo <+pipeline.variables.gl_tag>
          caching:
            enabled: false
            paths: []
          slsa_provenance:
            enabled: false
  variables:
    - name: gl_tag
      type: String
      description: ""
      required: false
      value: <+input>
