apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-12-29T17:01:53Z"
  generateName: df-mac-ng-
  labels:
    controller-revision-hash: df-mac-ng-fb5c95fbc
    harness.io/name: df-mac-ng
    statefulset.kubernetes.io/pod-name: df-mac-ng-0
  name: df-mac-ng-0
  namespace: harness-delegate-ng
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: df-mac-ng
    uid: fddb64c8-00af-4ada-9961-ce31289dd9e4
  resourceVersion: "902"
  uid: 4a26ecf6-7711-41c6-bb19-d58622bed097
spec:
  containers:
  - env:
    - name: JAVA_OPTS
      value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
        -Xms64M
    - name: ACCOUNT_ID
      value: SAsyUUHTTImuYSZ35HPDvw
    - name: ACCOUNT_SECRET
      value: afaea77d8244014c62d7484f8475f5be
    - name: MANAGER_HOST_AND_PORT
      value: https://app.harness.io
    - name: DEPLOY_MODE
      value: KUBERNETES
    - name: DELEGATE_NAME
      value: df-mac-ng
    - name: DELEGATE_TYPE
      value: KUBERNETES
    - name: PROXY_HOST
    - name: PROXY_PORT
    - name: PROXY_SCHEME
    - name: NO_PROXY
    - name: PROXY_MANAGER
      value: "true"
    - name: PROXY_USER
      valueFrom:
        secretKeyRef:
          key: PROXY_USER
          name: df-mac-ng-proxy
    - name: PROXY_PASSWORD
      valueFrom:
        secretKeyRef:
          key: PROXY_PASSWORD
          name: df-mac-ng-proxy
    - name: POLL_FOR_TASKS
      value: "false"
    - name: ENABLE_CE
      value: "false"
    - name: GRPC_SERVICE_ENABLED
      value: "true"
    - name: GRPC_SERVICE_CONNECTOR_PORT
      value: "8080"
    - name: VERSION_CHECK_DISABLED
      value: "false"
    - name: DELEGATE_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: DELEGATE_DESCRIPTION
    - name: DELEGATE_TAGS
    - name: DELEGATE_TASK_LIMIT
      value: "50"
    - name: DELEGATE_ORG_IDENTIFIER
    - name: DELEGATE_PROJECT_IDENTIFIER
    - name: INIT_SCRIPT
    - name: NEXT_GEN
      value: "true"
    - name: WATCHER_STORAGE_URL
      value: https://app.harness.io/public/prod/premium/watchers
    - name: WATCHER_CHECK_LOCATION
      value: current.version
    - name: REMOTE_WATCHER_URL_CDN
      value: https://app.harness.io/public/shared/watchers/builds
    - name: DELEGATE_STORAGE_URL
      value: https://app.harness.io
    - name: DELEGATE_CHECK_LOCATION
      value: delegateprod.txt
    - name: HELM_DESIRED_VERSION
    - name: USE_CDN
      value: "true"
    - name: CDN_URL
      value: https://app.harness.io
    - name: JRE_VERSION
      value: 1.8.0_242
    - name: HELM3_PATH
    - name: HELM_PATH
    - name: KUSTOMIZE_PATH
    - name: KUBECTL_PATH
    image: harness/delegate:latest
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - bash
        - -c
        - '[[ -e /opt/harness-delegate/msg/data/watcher-data && $(($(date +%s000)
          - $(grep heartbeat /opt/harness-delegate/msg/data/watcher-data | cut -d
          ":" -f 2 | cut -d "," -f 1))) -lt 300000 ]]'
      failureThreshold: 2
      initialDelaySeconds: 240
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: harness-delegate-instance
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - test
        - -s
        - delegate.log
      failureThreshold: 3
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-s4cf2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: df-mac-ng-0
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-s4cf2
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-12-29T17:01:53Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-12-29T17:01:53Z"
    message: 'containers with unready status: [harness-delegate-instance]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-12-29T17:01:53Z"
    message: 'containers with unready status: [harness-delegate-instance]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-12-29T17:01:53Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://658596de9067ad2a227f7c704d62076349ba21c44eebb57fabd51fb47597c312
    image: harness/delegate:latest
    imageID: docker-pullable://harness/delegate@sha256:8cac46dbe5249e8f19afaa35c1cd8777b8672b83c53e5d29959bb5777b86794c
    lastState:
      terminated:
        containerID: docker://658596de9067ad2a227f7c704d62076349ba21c44eebb57fabd51fb47597c312
        exitCode: 1
        finishedAt: "2021-12-29T17:05:39Z"
        reason: Error
        startedAt: "2021-12-29T17:05:35Z"
    name: harness-delegate-instance
    ready: false
    restartCount: 4
    started: false
    state:
      waiting:
        message: back-off 1m20s restarting failed container=harness-delegate-instance
          pod=df-mac-ng-0_harness-delegate-ng(4a26ecf6-7711-41c6-bb19-d58622bed097)
        reason: CrashLoopBackOff
  hostIP: 192.168.65.4
  phase: Running
  podIP: 10.1.0.6
  podIPs:
  - ip: 10.1.0.6
  qosClass: Guaranteed
  startTime: "2021-12-29T17:01:53Z"
