pipeline:
    name: Local Namespace Pipeline
    identifier: Local_Namespace_Pipeline
    projectIdentifier: DanF
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Deploy to Dev
              identifier: Deploy_to_Dev
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: nginxservice
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: manifests
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: DanFGithub
                                                    gitFetchType: Branch
                                                    paths:
                                                        - k8s/_story-devk8s/se-ecomm/se-recommendation.yaml
                                                    repoName: lna-demo
                                                    branch: master
                                            skipResourceVersioning: false
                  infrastructure:
                      environmentRef: Dev
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: danfmacconnector
                              namespace: env-dev
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: true
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
        - stage:
              name: Deploy to QA
              identifier: Deploy_to_QA
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: nginxservice
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: manifest
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: DanFGithub
                                                    gitFetchType: Branch
                                                    paths:
                                                        - k8s/_story-devk8s/se-ecomm/se-recommendation.yaml
                                                    repoName: lna-demo
                                                    branch: master
                                            skipResourceVersioning: false
                  infrastructure:
                      environmentRef: QA
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: danfmacconnector
                              namespace: env-qa
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: true
                  execution:
                      steps:
                          - step:
                                type: K8sRollingDeploy
                                name: Rollout Deployment
                                identifier: Rollout_Deployment
                                spec:
                                    skipDryRun: false
                                timeout: 10m
                      rollbackSteps: []
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
        - stage:
              name: Manual Approval
              identifier: Manual_Approval
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: HarnessApproval
                                name: manual approval
                                identifier: manual_approval
                                spec:
                                    approvalMessage: Please review the following information and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        userGroups:
                                            - DanFUserGroups
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                    approverInputs: []
                                timeout: 1d
                  serviceDependencies: []
              tags: {}
        - stage:
              name: Deploy to Prod
              identifier: Deploy_to_Prod
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: nginxservice
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: manifests
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: DanFGithub
                                                    gitFetchType: Branch
                                                    paths:
                                                        - k8s/_story-devk8s/se-ecomm/se-recommendation.yaml
                                                    repoName: lna-demo
                                                    branch: master
                                            skipResourceVersioning: false
                  infrastructure:
                      environmentRef: envprod
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: danfmacconnector
                              namespace: env-prod
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: true
                  execution:
                      steps:
                          - step:
                                type: K8sCanaryDeploy
                                name: Canary Deployment
                                identifier: Canary_Deployment
                                spec:
                                    skipDryRun: false
                                    instanceSelection:
                                        spec:
                                            percentage: 100
                                        type: Percentage
                                timeout: 10m
                      rollbackSteps: []
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
